/*

 GAMEBG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\bobst\Documents\GameBoy Code\gameTileDesign.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gameBgWidth 20
#define gameBgHeight 18
#define gameBgBank 0

extern unsigned char gameBg[];

/* End of GAMEBG.H */
